apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ngrok-secret
  namespace: ngrok-operator
spec:
  template:
    type: Opaque
    metadata:
      name: ngrok-secret
      namespace: ngrok-operator
  encryptedData:
    authtoken: 'AgAhS0NanU0kx5bqy0aN+Xl8HjMwMaBZuqDKdMMjRt1dl8ftDzSu573ZS930/xjzNDH0CeQLvFZOz7VlElN6FX05fz3cXLYxzj26O9YwsFJZu2dhas3vkImFJA3yF4OhGyy9BIg5I60hxbmPaSPXzXb+AVHa+hZp/YF06LUqpthMATV1zA32v6yM5tL2+iwbYJfcPKm+YWSABvM3FPtvLxXlR2k/VvLXF7vFqtTqt8jr40h+YSXhpVAr1trVToAHVZbycQ8W1uhAO44SpYV25XYT3ZrL1PwcBuwTMQpRZJZgtyE86hp81ty8GAHUvBqbQiX3w4Oz3PSvLEy6Ko++g5OCmxiOqwf+kv/54ie4V/L6NeRrTnSf3tvlKADTy77K4EHP40GAyzMQVuF0DONHCfAX6VEfIHvekCIC5JmryszeKuVze/krwXzoOifwVXxXcJiuMUt9dESUHh7jmarNOKX4lp2lmdUDMcqHAXHzOKgc6lqASYhtI5U5Gw2zMh0Wg/L3ZkOJcgX+R9Ja8F8Mp8590DrYPAFHRknCw08zlfLk5pmgEkzroBCnQkR/elPqSi0dfWa/MOQIjpWzRXnDCLlC1hB4Gq4z3VLS1zoOjjaShAYPblADQ6sXHcOpr9QGcbl8PD0N3Ep7UZwP/C2XN5OluqhMc36nB2Oy1aNu5dG2snSRGTO+NDEye3KGKcJl2zeqqncbltPnP7i3BJzMnCSN+w8iX/MATI+RmewwsV0JbGXwmw7AkK2PMQ2JB1nP8dJo'