# Modified target port to 8080 to match! and fit Snyk Vulnerability fix in Deployment.yaml

apiVersion: v1
kind: Service     # Manifest defintion tyype
metadata:
  name: interview-app
  namespace: default
  labels:
    app: interview-app
spec:
  type: NodePort   # For K3s (so i can access it via K3s:<nodePort>) 
  selector:
    app: interview-app
  ports:
    - name: http        # Regular port 80 for http
      protocol: TCP     # Network protocol type
      port: 8080          # The service port 
      targetPort: 8080  # It has to match the port in my deployment file
      nodePort: 31080   # Optional: i will manually add a port; or else K8s assigns one for me
